### ISSUE TITLE
Mutual kill is prevented

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#8]
Hello
When 2 players shoot each other at the same time, they don't both die, one does but the other one loses some health.

Noticed when doing melee and using bolt weapon
`scr_mm_instantkill`, `scr_mm_pistolkill` and `scr_mm_meleekill` are enabled in this case.

I didn't have this effect when taking over `finishPlayerDamage` before, when using the (a bit modified to re-enable instantkill) misaligned hitmarker from vcodmods website.
(hoping this information could help identifying the cause)

Is this effect intended ? Is it caused by `eAttacker thread _showHitm`... ?
I can't find in there code where this is managed.

Or is it that they don't shoot at the exact same time ?

**Comment by cato-a** [comment]
Hi, it is very rare to have 2 players kill eachother at the same time. CoDaM is quite big and bulky causing overhead making it even more rare for this happen, and the slower the host, the rarer it will be.

MiscMod doesn't do anything to limit players killing eachother that I know of. If instantkill is enabled and both hits are registered by the server, the chances should be higher that you get 2 players kill eachother.

**Comment by raphael12345678** [comment]
It happened again this morning doing melee (it was a showdown)
I don't understand why I just lost some health
I don't close in case someone can help about it in the future

Imo mutual kill is pretty funny, otherwise it's not very fair for the only one who dies but did hit with instantkill enabled
Sorry if it's not MiscMod causing this, but I really think it is
